### ISSUE TITLE
Does sylvia 0.3.1 support the migrate contract?

### ISSUE THREAD

**Issue by Smea1** [CosmWasm/sylvia#100]
I would like to ask if there is any msg instructions related to the migration contract, if there is, it will be very grateful

**Comment by jawoznia** [comment]
It is currently possible to generate `MigrateMsg` using `#[msg(migrate)]`. Only one MigrateMsg can be defined per `contract`.
Please check `contracts/cw20-base/src/contract.rs`.

Support for migration will be developed more under #25 and #26. Usage of `#[msg(migrate)]` will then be described in [sylvia book](https://cosmwasm.github.io/sylvia-book/index.html)

**Comment by hashedone** [comment]
Close in favor of #25 and #26
