### ISSUE TITLE
Create a cargo template for sylvia

### ISSUE THREAD

**Issue by hashedone** [CosmWasm/sylvia#110]

**Comment by jawoznia** [comment]
What I would like to see first is to generate simple contract with maybe `exec` and `query`. Next to it I would appreciate the example test.

```rust
pub struct CounterContract {
    pub count: Item<'static, u64>,
}

#[contract]
impl CounterContract {
    pub fn new() -> Self {
        Self {
            count: Item::new("count"),
        }
    }

    #[msg(instantiate)]
    fn instantiate(&self, ctx: InstantiateCtx) -> StdResult<Response> {
        self.count.save(ctx.deps.storage, &0)?;
        Ok(Response::new())
    }

    #[msg(exec)]
    fn instantiate(&self, ctx: ExecCtx) -> StdResult<Response> {
        self.count.save(ctx.deps.storage, &1)?;
        Ok(Response::new())
    }

    #[msg(query)]
    fn query(&self, ctx: QueryCtx) -> StdResult<CountResponse> {
        let count = self.count.load(ctx.deps.storage)?;
        Ok(CountResponse { count })
    }
}

#[cfg(test)]
mod tests {
    
#[test]
fn example() {
...
}
}
```

**Comment by jawoznia** [comment]
Next I think it would be nice to have an example using `Interface` and maybe one more with only `Interface`

**Comment by uint** [comment]
It's not clear to me what the scope of this ticket is, but I have a starting point:

https://github.com/CosmWasm/sylvia-template

Before packing it with more example code: from what I remember, some users of `cw-template` previously didn't like that there was a lot of stuff they had to remove every time they generated a project. You might want to prioritize the "quickstart a project" part and not the "teach people Sylvia" part (unless it's [hidden behind a config option](https://github.com/CosmWasm/cw-template/blob/main/cargo-generate.toml#L7-L10)).

**Comment by uint** [comment]
Also, should this be under a public domain license? It'd be a bit strange for users of a simple template to be worrying about licenses and attributions.
