### ISSUE TITLE
Add `Deref` and `DerefMut` for the `App`

### ISSUE THREAD

**Issue by hashedone** [CosmWasm/sylvia#138]
As our `App` is really only a smart pointer over an `App` (providing `Rc<RefCell<_>>`, and it even has the `app` and `app_mut` functions, I would add `Deref<Target=cw_multi_test::App>` and `DerefMut` implementations to it.

**Comment by jawoznia** [comment]
closing in favor of #154 as Deref won't work with RefCell as we wanted it to
