### ISSUE TITLE
Implement Querier directly on sylvia::multitest::App

### ISSUE THREAD

**Issue by jawoznia** [CosmWasm/sylvia#154]
Let's implement the [QuerierWrapper](https://docs.rs/cosmwasm-std/latest/cosmwasm_std/struct.QuerierWrapper.html) directly on our `App`, so we can provide the direct `wrap()` function on `Querier` (and let's rename it to `querier` as the `wrap` name without the context is confusing to me.

_Originally posted by @hashedone in https://github.com/CosmWasm/sylvia/pull/150#discussion_r1221318204_

**Comment by hashedone** [comment]
please don't use backticks for links; you can do `[human readable text](URL)`, for example here: `[QuerierWrapper](https://docs.rs/cosmwasm-std/latest/cosmwasm_std/struct.QuerierWrapper.html)` (which renders as: [QuerierWrapper](https://docs.rs/cosmwasm-std/latest/cosmwasm_std/struct.QuerierWrapper.html))
