### ISSUE TITLE
Warn on missing `#[custom(msg=...)]` or `ExecC` on trait

### ISSUE THREAD

**Issue by hashedone** [CosmWasm/sylvia#162]
We want a warning message on interfaces not allowing for custom message specification. The `#[custom(msg=cosmwasm_std::Empty)]` should explicitly shut down this warning.

**Comment by jawoznia** [comment]
Since `emit_warning!` works only on nightly and cause our test to some weird fail we will postpone this task and remove from #157 requirements

**Comment by hashedone** [comment]
Same for `QueryC + #[custom(query=...)]`
