### ISSUE TITLE
Refactor some if-else chains to match or functions on matched item

### ISSUE THREAD

**Issue by hashedone** [CosmWasm/sylvia#169]
I am not a fan of this if-else chain. I am pretty sure it should be a match or even a function like `MsgType::generate_message_variant(...)` (not sure about this one, as maybe it is not the best place to put this).

Here you did only minimal changes on this, but let's fix it up in some later refactor (I'll create a task).

Especially since those things look identical. Really. I see the difference, but I think we could simplify it. Not mentioning last else is bullcrap here, I don't see which patterns are not covered; it frustrates me.

_Originally posted by @hashedone in https://github.com/CosmWasm/sylvia/pull/156#discussion_r1224293099_

Also, we should take a look through the codebase to find other instances of similar chains.

**Comment by kulikthebird** [comment]
I'm closing this issue since the code it references has already been refactored.
