### ISSUE TITLE
Figure out a way to test coverage validation in Sylvia

### ISSUE THREAD

**Issue by hashedone** [CosmWasm/sylvia#22]

**Comment by jawoznia** [comment]
Current findings:

https://doc.rust-lang.org/rustc/instrument-coverage.html
![image](https://user-images.githubusercontent.com/24798491/186182426-c9bf25cd-fea4-42e5-9fce-c4df82bd16bc.png)

Locally configured and generated report using LLVM. Need more work to find out how to introduce it to CI and allow to validate if coverage raise or fall after PR.

**Comment by jawoznia** [comment]
1. Run RUSTFLAGS="-C instrument-coverage" cargo buildFull report can be generated via

llvm-cov-15 report -Xdemangler=rustfilt target/debug/libsylvia_derive.so \
    -instr-profile=default.profdata

**Comment by hashedone** [comment]
Did you check this tool https://docs.rs/runtime-macros-derive/latest/runtime_macros_derive/?

**Comment by jawoznia** [comment]
Unfortunately it won't work as our macros requires 2 TokenStreams (attr and item) while runtime_macros_derive expect our macros to require only one TokenStream.

**Comment by jawoznia** [comment]
There is a wrapper over llvm - https://crates.io/crates/cargo-llvm-cov
It is stated that proc-macros are being covered by this.

**Comment by jawoznia** [comment]
Contacted authors of https://docs.rs/runtime-macros-derive/latest/runtime_macros_derive/ regarding support for multiple TS inputs to macros. Will continue if they will introduce this feature.

**Comment by jawoznia** [comment]
I guess we can close this issue due to delivery of #33  and #48.
@hashedone please comment if nothing else should be done in terms of CI development in this task

**Comment by jawoznia** [comment]
Closing due to delivery of #33 and #48
