### ISSUE TITLE
Support features for cw-multi-test

### ISSUE THREAD

**Issue by whalelephant** [CosmWasm/sylvia#262]
Currently using cw-multi-test v0.18.0 in deps does not automatically include the updated [features](https://github.com/CosmWasm/cw-multi-test/blob/4bc617f899a7f8d4257e9633d4a0340628dfee61/Cargo.toml#L20). 

As a framework around it, either those can be specified or perhaps default to the latest.

**Comment by jawoznia** [comment]
@whalelephant please check #267 and let me know if there are anymore features you think `sylvia` should expose.

**Comment by whalelephant** [comment]
@jawoznia checked, all good for me thank you!
