### ISSUE TITLE
Internal refactor

### ISSUE THREAD

**Issue by jawoznia** [CosmWasm/sylvia#295]
This is a collector of all ideas/issues we would like to fix in `sylvia` internals that are not API breaking.

# Issues

- [x] #288

**Comment by kulikthebird** [comment]
In https://github.com/CosmWasm/sylvia/pull/282 and https://github.com/CosmWasm/sylvia/pull/283 we started a discussion regarding:
* moving all querier-related implementation to module querier
* moving all remote-related implementation to module remote
* moving all multitest-related implementation to module multitest
* avoid using `AddSelfPath`  and similar structures in favor of a better model generated by the parser
