### ISSUE TITLE
Entry points generation

### ISSUE THREAD

**Issue by hashedone** [CosmWasm/sylvia#38]
Writing entry points is very tedious right now. Create a new contract instance, and call dispatch on it.  Maybe we would be able to generate it somehow.

**Comment by jawoznia** [comment]
I think the best approach would be to use `#[Contract]` macro to generate the `entry points` and user can expose them in `lib.rs` or they will be automatically exposed if the user will define the contract in the `lib.rs` file.

We could also create new macro for this purpose, call it and pass to it the module in which the contract is defined.
