### ISSUE TITLE
Verify there are no messages collisions for exec and query messages

### ISSUE THREAD

**Issue by hashedone** [CosmWasm/sylvia#8]
Follow up of #7 

Having the `const fn messages() -> [&'static str; N]` function, now some code should be generated in the `distpatch` of a "glue message" to check if there are no messages collisions. Then it should be asserted and assigned to some `const` value to ensure the check is happening only in compile time. Something like this is to be generated at the very beginning of `dispatch`:

```rust
const _: () = {
  const no_collisions: bool = /* do magic */;
  assert!(no_collistions)
};
```

As it is assigned to `const`, it is compiled time evaluated and no overhead should be happening in runtime.

**Comment by jawoznia** [comment]
Blocked by #10
