### ISSUE TITLE
Improve `dispatch` generation to know what message dispatch to basing on the top level field.

### ISSUE THREAD

**Issue by hashedone** [CosmWasm/sylvia#9]
Follow up of #7 

The messages in the contract build with Sylvia are assumed to be in the form of:

```json
{
  "message_type": { ... }
}
```

The `message_type` is determining what message is actually sent. Every trait being `#[interface]` for Sylvia generates structures which are able to deserialize its collection of `message_type`s.

However, for now, generated `dispatch` function is trying to just deserialize the whole message to one of the sub-messages ones by one which might be an unnecessary overhead. Having `const fn messages() -> [&'static str; N]` function for every message type, it is possible  to do the following in the `dispatch` function:
1. Extract the "message_type" from the message send
2. Check which `message()` function returns the array containing "message_type" - as messages returned by `message()` are already sorted, it can be done quickly with binary search
3. Try to deserialize only to the final message type - obviously, it still can fail (as the message may be malformed)

The easy way is to deserialize to `Value`, then check on "message_type" and proceed with deserialization, but I think that it should be possible with custom hand-made `Deserialize` implementation for even more overhead reduction - it is to be verified and tried.

**Comment by jawoznia** [comment]
Delivered under #44
